# Generated by Django 5.0 on 2024-01-03 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("d_name", models.CharField(max_length=100)),
                ("d_email", models.EmailField(max_length=254)),
                ("d_password", models.CharField(max_length=100)),
                ("d_username", models.CharField(max_length=50)),
                ("d_mobile", models.CharField(max_length=15)),
                ("d_special", models.CharField(max_length=50)),
                (
                    "d_gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("d_city", models.CharField(max_length=50)),
                ("d_state", models.CharField(max_length=50)),
                ("d_address", models.TextField()),
                ("d_code", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
