# Generated by Django 5.0 on 2024-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0004_login_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="password",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
