# Generated by Django 5.0 on 2024-01-04 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0005_login_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="login",
            name="password",
        ),
    ]
