# Generated by Django 5.0 on 2024-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0006_remove_login_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="d_image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
