# Generated by Django 5.0 on 2024-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0007_doctor_d_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="p_image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
