# Generated by Django 5.0 on 2024-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0009_appointment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="appointment_date",
            new_name="apply_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="p_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="p_mobile",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="p_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointment",
            name="selected_doctor",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
