# Generated by Django 5.0 on 2024-01-14 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0010_rename_appointment_date_appointment_apply_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="selected_doctor",
            new_name="selected_dpt",
        ),
    ]
