# Generated by Django 5.0 on 2024-01-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0013_alter_appointment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="apply_date",
            new_name="appointment_date",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
