# Generated by Django 5.0 on 2024-01-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0014_rename_apply_date_appointment_appointment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor_ap",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
