# Generated by Django 5.0 on 2024-01-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0015_appointment_doctor_ap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.TimeField(),
        ),
    ]
