# Generated by Django 5.0 on 2024-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0017_alter_appointment_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(max_length=15),
        ),
    ]
