# Generated by Django 5.0 on 2024-01-17 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0018_alter_appointment_appointment_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment_final",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_token", models.CharField(max_length=255)),
                ("p_name", models.CharField(max_length=255)),
                ("p_email", models.EmailField(max_length=254)),
                ("p_mobile", models.CharField(max_length=15)),
                ("appointment_date", models.DateField()),
                ("selected_dpt", models.CharField(max_length=255)),
                ("doctor_ap", models.CharField(max_length=255)),
                ("appointment_time", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
