# Generated by Django 5.0 on 2024-01-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0021_alter_appointment_final_p_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment_final",
            name="p_token",
            field=models.CharField(max_length=5),
        ),
    ]
