# Generated by Django 5.0 on 2024-01-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0022_alter_appointment_final_p_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="p_token",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
