# Generated by Django 5.0 on 2024-01-18 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0023_appointment_p_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment_final",
        ),
    ]
